# Generated by Django 4.2.2 on 2023-06-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.CharField(max_length=50)),
                ('Area_Especializacion', models.CharField(max_length=50)),
                ('ESTADO', models.BooleanField()),
            ],
            options={
                'db_table': 'CONSULTOR',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nit', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Estado', models.BooleanField()),
            ],
            options={
                'db_table': 'METODO_PAGO',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Estado', models.BooleanField()),
            ],
            options={
                'db_table': 'TIPO_SERVICIO',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Finalizacion', models.DateField()),
                ('Estado', models.BooleanField()),
                ('Id_Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
            options={
                'db_table': 'PROYECTO',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Factura', models.DateField()),
                ('Valor', models.FloatField()),
                ('Id_M_Pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.metodopago')),
            ],
            options={
                'db_table': 'FACTURA',
            },
        ),
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.BooleanField()),
                ('Id_Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
                ('Id_T_Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
            ],
            options={
                'db_table': 'CONSULTORIA',
            },
        ),
        migrations.CreateModel(
            name='ConsEmp',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('id_Consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultoria')),
                ('id_Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
            options={
                'db_table': 'CONS_EMP',
            },
        ),
        migrations.CreateModel(
            name='ConsCons',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultor')),
                ('Id_Consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultoria')),
            ],
            options={
                'db_table': 'CONS_CONS',
            },
        ),
    ]
