# Generated by Django 4.1.5 on 2023-05-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conscons_table_alter_consemp_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Empresa', models.IntegerField()),
                ('Nit_Empresa', models.CharField(max_length=20)),
                ('Nombre_Empresa', models.CharField(max_length=50)),
                ('Direccion_Empresa', models.CharField(max_length=100)),
                ('Sector_Empresa', models.CharField(max_length=50)),
                ('Correo_Empresa', models.CharField(max_length=50)),
                ('ID_Proyecto', models.IntegerField()),
                ('Nombre_Proyecto', models.CharField(max_length=50)),
                ('Descripcion_Proyecto', models.CharField(max_length=200)),
                ('Fecha_Inicio_Proyecto', models.DateField()),
                ('Fecha_Finalizacion_Proyecto', models.DateField()),
                ('Id_Empresa_Proyecto', models.IntegerField()),
                ('Estado_Proyecto', models.BooleanField()),
                ('ID_M_Pago', models.IntegerField()),
                ('Nombre_M_Pago', models.CharField(max_length=50)),
                ('Descripcion_M_Pago', models.CharField(max_length=100)),
                ('Estado_M_Pago', models.BooleanField()),
                ('ID_Factura', models.IntegerField()),
                ('Fecha_Factura', models.DateField()),
                ('Valor_Factura', models.FloatField()),
                ('Id_M_Pago_Factura', models.IntegerField()),
                ('ID_T_Servicio', models.IntegerField()),
                ('Nombre_T_Servicio', models.CharField(max_length=50)),
                ('Descripcion_T_Servicio', models.CharField(max_length=100)),
                ('Estado_T_Servicio', models.BooleanField()),
                ('ID_Consultoria', models.IntegerField()),
                ('Id_Factura_Consultoria', models.IntegerField()),
                ('Id_T_Servicio_Consultoria', models.IntegerField()),
                ('Estado_Consultoria', models.BooleanField()),
                ('ID_CONS_EMP', models.IntegerField()),
                ('id_Consultoria_CONS_EMP', models.IntegerField()),
                ('id_Empresa_CONS_EMP', models.IntegerField()),
                ('ID_Consultor', models.IntegerField()),
                ('Nombre_Consultor', models.CharField(max_length=100)),
                ('Telefono_Consultor', models.CharField(max_length=10)),
                ('Correo_Consultor', models.CharField(max_length=50)),
                ('Area_Especializacion_Consultor', models.CharField(max_length=50)),
                ('ESTADO_Consultor', models.BooleanField()),
                ('ID_CONS_CONS', models.IntegerField()),
                ('Id_Consultoria_CONS_CONS', models.IntegerField()),
                ('Id_Consultor_CONS_CONS', models.IntegerField()),
            ],
            options={
                'db_table': 'TablaInicial',
            },
        ),
    ]
