# Generated by Django 4.2.2 on 2023-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conscons_creado_en_conscons_modificado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='creado_en',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modificado_en',
            field=models.DateTimeField(null=True),
        ),
    ]
