# Generated by Django 4.1.5 on 2023-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_consemp_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conscons',
            name='modificado_en',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consemp',
            name='modificado_en',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consultor',
            name='modificado_en',
            field=models.DateTimeField(null=True),
        ),
    ]
