# Generated by Django 4.1.5 on 2023-06-05 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_conscons_modificado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganancia',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
