# Generated by Django 4.1.5 on 2023-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tablainicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO_FACTURA', models.IntegerField()),
                ('PRECIO', models.IntegerField()),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Prueba',
            },
        ),
    ]
