# Generated by Django 4.1.5 on 2023-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ganancia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganancia',
            name='ID',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
