# Generated by Django 4.2.2 on 2023-06-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_factura_aumento_alter_consultoria_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganancia',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.FloatField()),
                ('Descuentos', models.FloatField()),
                ('id_Factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganancias', to='app.factura')),
            ],
            options={
                'db_table': 'GANANCIA',
            },
        ),
    ]
