# Generated by Django 4.1.5 on 2023-06-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='TablaInicial',
        ),
    ]
