# Generated by Django 4.2.2 on 2023-06-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_factura_aumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='aumento',
            field=models.FloatField(default=0.6),
        ),
    ]
